### ISSUE TITLE
discord integration

### ISSUE THREAD

**Issue by TheUtopianPlayz** [hachkingtohach1/ReportSystem#1]
would be amazing if u could add discord integration
that way the report could be sent to a channel in discord via a webhook similarly to the way that the MCPEtoDiscord plugin works for chat logs

{player reporting} Reported {reported player} for {reason}

or something along those lines, would be great for staff purposes

**Comment by hachkingtohach1** [comment]
okay i will look and do it later !! Thank you for submitting comments: 3
